version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      PORT: 3001
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (r) => {if (r.statusCode !== 200) throw new Error(r.statusCode)})"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - wobot-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=http://localhost:3001
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:3001
    depends_on:
      - backend
    networks:
      - wobot-network
    restart: unless-stopped

networks:
  wobot-network:
    driver: bridge
